#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output DP-4 --primary --mode 3440x1440 --rate 144.00 --output DP-2 --mode 2560x1440 --rate 144.00 --above DP-4

MONITORS=( $(bspc query --monitors) )

bspc wm --reorder-monitors DP-4 DP-2
bspc monitor DP-4 -d 1 2 3 4 
bspc monitor DP-2 -d 5 6 7 8 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

sh /home/zach/.config/polybar/launch.sh

feh --bg-scale --randomize $HOME/images/wallpaper/wallpapers/
picom --config $HOME/.config/picom/picom.conf
xsetroot -cursor_name left_ptr
